//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Gabana.ORM.MerchantDB
{
	/// <summary>
	/// Database       : MerchantDBT4
	/// Data Source    : MerchantDBT4
	/// Server Version : 3.24.0
	/// </summary>
	public partial class MerchantDB : LinqToDB.Data.DataConnection
	{
		public ITable<AppConfig>             AppConfigs             { get { return this.GetTable<AppConfig>(); } }
		public ITable<Branch>                Branches               { get { return this.GetTable<Branch>(); } }
		public ITable<BranchPolicy>          BranchPolicies         { get { return this.GetTable<BranchPolicy>(); } }
		public ITable<CashTemplate>          CashTemplates          { get { return this.GetTable<CashTemplate>(); } }
		public ITable<Category>              Categories             { get { return this.GetTable<Category>(); } }
		public ITable<Customer>              Customers              { get { return this.GetTable<Customer>(); } }
		public ITable<DataBaseInfo>          DataBaseInfo           { get { return this.GetTable<DataBaseInfo>(); } }
		public ITable<DeviceSystemSeqNo>     DeviceSystemSeqNoes    { get { return this.GetTable<DeviceSystemSeqNo>(); } }
		public ITable<DeviceTranRunningNo>   DeviceTranRunningNoes  { get { return this.GetTable<DeviceTranRunningNo>(); } }
		public ITable<DiscountTemplate>      DiscountTemplates      { get { return this.GetTable<DiscountTemplate>(); } }
		public ITable<GiftVoucher>           GiftVouchers           { get { return this.GetTable<GiftVoucher>(); } }
		public ITable<Item>                  Items                  { get { return this.GetTable<Item>(); } }
		public ITable<ItemExSize>            ItemExSizes            { get { return this.GetTable<ItemExSize>(); } }
		public ITable<ItemOnBranch>          ItemOnBranches         { get { return this.GetTable<ItemOnBranch>(); } }
		public ITable<MemberType>            MemberTypes            { get { return this.GetTable<MemberType>(); } }
		public ITable<Merchant>              Merchants              { get { return this.GetTable<Merchant>(); } }
		public ITable<MerchantConfig>        MerchantConfigs        { get { return this.GetTable<MerchantConfig>(); } }
		public ITable<MyQrCode>              MyQrCodes              { get { return this.GetTable<MyQrCode>(); } }
		public ITable<Note>                  Notes                  { get { return this.GetTable<Note>(); } }
		public ITable<NoteCategory>          NoteCategories         { get { return this.GetTable<NoteCategory>(); } }
		public ITable<ScriptAlterMerchantDB> ScriptAlterMerchantDbs { get { return this.GetTable<ScriptAlterMerchantDB>(); } }
		public ITable<SystemInfo>            SystemInfo             { get { return this.GetTable<SystemInfo>(); } }
		public ITable<SystemRevisionNo>      SystemRevisionNoes     { get { return this.GetTable<SystemRevisionNo>(); } }
		public ITable<Tran>                  Trans                  { get { return this.GetTable<Tran>(); } }
		public ITable<TranDetailItem>        TranDetailItems        { get { return this.GetTable<TranDetailItem>(); } }
		public ITable<TranDetailItemTopping> TranDetailItemToppings { get { return this.GetTable<TranDetailItemTopping>(); } }
		public ITable<TranPayment>           TranPayments           { get { return this.GetTable<TranPayment>(); } }
		public ITable<TransPoint>            TransPoints            { get { return this.GetTable<TransPoint>(); } }
		public ITable<TranTradDiscount>      TranTradDiscounts      { get { return this.GetTable<TranTradDiscount>(); } }
		public ITable<UserAccountInfo>       UserAccountInfo        { get { return this.GetTable<UserAccountInfo>(); } }


		public MerchantDB(string pathDB)
		: base(LinqToDB.ProviderName.SQLiteMS, DbHelper.MerchantDB(pathDB))
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("AppConfig")]
	public partial class AppConfig
	{
		[PrimaryKey, NotNull    ] public string    CfgKey     { get; set; } // varchar(50)
		[Column,        Nullable] public string    CfgString  { get; set; } // varchar(255)
		[Column,        Nullable] public long?     CfgInteger { get; set; } // integer
		[Column,        Nullable] public decimal?  CfgFloat   { get; set; } // numeric
		[Column,        Nullable] public DateTime? CfgDate    { get; set; } // date
	}

	[Table("Branch")]
	public partial class Branch
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID      { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysBranchID     { get; set; } // integer
		[Column,           Nullable] public long?    Ordinary        { get; set; } // integer
		[Column,        NotNull    ] public string   BranchID        { get; set; } // varchar(25)
		[Column,        NotNull    ] public string   BranchName      { get; set; } // varchar(100)
		[Column,           Nullable] public string   Address         { get; set; } // varchar(250)
		[Column,           Nullable] public long?    ProvincesId     { get; set; } // integer
		[Column,           Nullable] public long?    AmphuresId      { get; set; } // integer
		[Column,           Nullable] public long?    DistrictsId     { get; set; } // integer
		[Column,        NotNull    ] public char     Status          { get; set; } // varchar(1)
		[Column,        NotNull    ] public char     DisplayLanguage { get; set; } // varchar(1)
		[Column,           Nullable] public decimal? Lat             { get; set; } // numeric
		[Column,           Nullable] public decimal? Lng             { get; set; } // numeric
		[Column,           Nullable] public string   Email           { get; set; } // varchar(100)
		[Column,           Nullable] public string   Tel             { get; set; } // varchar(100)
		[Column,           Nullable] public string   Line            { get; set; } // varchar(100)
		[Column,           Nullable] public string   Facebook        { get; set; } // varchar(100)
		[Column,           Nullable] public string   Instagram       { get; set; } // varchar(100)
		[Column,           Nullable] public string   TaxBranchName   { get; set; } // varchar(255)
		[Column,           Nullable] public string   TaxBranchID     { get; set; } // varchar(50)
		[Column,           Nullable] public string   LinkProMaxxID   { get; set; } // varchar(50)
		[Column,           Nullable] public string   Comments        { get; set; } // varchar(255)
	}

	[Table("BranchPolicy")]
	public partial class BranchPolicy
	{
		[PrimaryKey(0), NotNull] public long   MerchantID  { get; set; } // integer
		[PrimaryKey(1), NotNull] public string UserName    { get; set; } // varchar(50)
		[PrimaryKey(2), NotNull] public long   SysBranchID { get; set; } // integer
	}

	[Table("CashTemplate")]
	public partial class CashTemplate
	{
		[PrimaryKey(0), NotNull] public long     MerchantID     { get; set; } // integer
		[PrimaryKey(1), NotNull] public long     CashTemplateNo { get; set; } // integer
		[Column,        NotNull] public decimal  Amount         { get; set; } // numeric
		[Column,        NotNull] public DateTime DateModified   { get; set; } // datetime
	}

	[Table("Category")]
	public partial class Category
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID      { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysCategoryID   { get; set; } // integer
		[Column,           Nullable] public long?    Ordinary        { get; set; } // integer
		[Column,        NotNull    ] public string   Name            { get; set; } // varchar(100)
		[Column,        NotNull    ] public DateTime DateCreated     { get; set; } // datetime
		[Column,        NotNull    ] public DateTime DateModified    { get; set; } // datetime
		[Column,        NotNull    ] public char     DataStatus      { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  FWaitSending    { get; set; } // numeric
		[Column,        NotNull    ] public DateTime WaitSendingTime { get; set; } // datetime
		[Column,           Nullable] public string   LinkProMaxxID   { get; set; } // varchar(50)
	}

	[Table("Customer")]
	public partial class Customer
	{
		[PrimaryKey(0), NotNull    ] public long      MerchantID         { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long      SysCustomerID      { get; set; } // integer
		[Column,        NotNull    ] public string    CustomerName       { get; set; } // varchar(255)
		[Column,           Nullable] public long?     Ordinary           { get; set; } // integer
		[Column,           Nullable] public string    CustomerID         { get; set; } // varchar(50)
		[Column,           Nullable] public string    ShortName          { get; set; } // varchar(50)
		[Column,           Nullable] public string    PicturePath        { get; set; } // varchar(255)
		[Column,           Nullable] public string    ThumbnailPath      { get; set; } // varchar(255)
		[Column,           Nullable] public string    PictureLocalPath   { get; set; } // varchar(255)
		[Column,           Nullable] public string    ThumbnailLocalPath { get; set; } // varchar(255)
		[Column,           Nullable] public long?     MemberTypeNo       { get; set; } // integer
		[Column,           Nullable] public string    EMail              { get; set; } // varchar(320)
		[Column,           Nullable] public string    Mobile             { get; set; } // varchar(50)
		[Column,           Nullable] public string    LineID             { get; set; } // varchar(255)
		[Column,        NotNull    ] public char      Gender             { get; set; } // varchar(1)
		[Column,           Nullable] public DateTime? BirthDate          { get; set; } // date
		[Column,           Nullable] public string    Address            { get; set; } // varchar(255)
		[Column,           Nullable] public long?     ProvincesId        { get; set; } // integer
		[Column,           Nullable] public long?     AmphuresId         { get; set; } // integer
		[Column,           Nullable] public long?     DistrictsId        { get; set; } // integer
		[Column,           Nullable] public string    IDCard             { get; set; } // varchar(20)
		[Column,        NotNull    ] public decimal   BalancePoint       { get; set; } // numeric
		[Column,           Nullable] public string    Comments           { get; set; } // varchar(255)
		[Column,        NotNull    ] public DateTime  LastDateModified   { get; set; } // datetime
		[Column,        NotNull    ] public string    UserLastModified   { get; set; } // varchar(50)
		[Column,        NotNull    ] public char      DataStatus         { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal   FWaitSending       { get; set; } // numeric
		[Column,        NotNull    ] public DateTime  WaitSendingTime    { get; set; } // datetime
		[Column,           Nullable] public string    MemberCardNo       { get; set; } // varchar(16)
		[Column,           Nullable] public string    LinkProMaxxID      { get; set; } // varchar(50)
	}

	[Table("DataBaseInfo")]
	public partial class DataBaseInfo
	{
		[PrimaryKey, NotNull    ] public string KeyDBInfo  { get; set; } // varchar(50)
		[Column,        Nullable] public string DataDBInfo { get; set; } // varchar(255)
	}

	[Table("DeviceSystemSeqNo")]
	public partial class DeviceSystemSeqNo
	{
		[PrimaryKey(0), NotNull] public long MerchantID   { get; set; } // integer
		[PrimaryKey(1), NotNull] public long DeviceNo     { get; set; } // integer
		[PrimaryKey(2), NotNull] public long SystemID     { get; set; } // integer
		[Column,        NotNull] public long LastSysSeqNo { get; set; } // integer
	}

	[Table("DeviceTranRunningNo")]
	public partial class DeviceTranRunningNo
	{
		[PrimaryKey(0), NotNull] public long MerchantID        { get; set; } // integer
		[PrimaryKey(1), NotNull] public long SysBranchID       { get; set; } // integer
		[PrimaryKey(2), NotNull] public long DeviceNo          { get; set; } // integer
		[Column,        NotNull] public long TranLastRunningNo { get; set; } // integer
	}

	[Table("DiscountTemplate")]
	public partial class DiscountTemplate
	{
		[PrimaryKey(0), NotNull] public long     MerchantID          { get; set; } // integer
		[PrimaryKey(1), NotNull] public long     SysDiscountTemplate { get; set; } // integer
		[Column,        NotNull] public string   TemplateName        { get; set; } // varchar(100)
		[Column,        NotNull] public string   TemplateType        { get; set; } // varchar(2)
		[Column,        NotNull] public string   FmlDiscount         { get; set; } // varchar(50)
		[Column,        NotNull] public DateTime DateCreated         { get; set; } // datetime
		[Column,        NotNull] public DateTime DateModified        { get; set; } // datetime
		[Column,        NotNull] public char     DataStatus          { get; set; } // varchar(1)
		[Column,        NotNull] public decimal  FWaitSending        { get; set; } // numeric
		[Column,        NotNull] public DateTime WaitSendingTime     { get; set; } // datetime
	}

	[Table("GiftVoucher")]
	public partial class GiftVoucher
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID       { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public string   GiftVoucherCode  { get; set; } // varchar(25)
		[Column,        NotNull    ] public string   GiftVoucherName  { get; set; } // varchar(100)
		[Column,           Nullable] public long?    Ordinary         { get; set; } // integer
		[Column,        NotNull    ] public string   FmlAmount        { get; set; } // varchar(25)
		[Column,        NotNull    ] public DateTime DateCreated      { get; set; } // datetime
		[Column,        NotNull    ] public DateTime DateModified     { get; set; } // datetime
		[Column,        NotNull    ] public string   UserNameModified { get; set; } // varchar(50)
	}

	[Table("Item")]
	public partial class Item
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID          { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysItemID           { get; set; } // integer
		[Column,        NotNull    ] public string   ItemName            { get; set; } // varchar(255)
		[Column,           Nullable] public long?    Ordinary            { get; set; } // integer
		[Column,           Nullable] public long?    SysCategoryID       { get; set; } // integer
		[Column,           Nullable] public string   ItemCode            { get; set; } // varchar(50)
		[Column,           Nullable] public string   ShortName           { get; set; } // varchar(50)
		[Column,           Nullable] public string   PicturePath         { get; set; } // varchar(255)
		[Column,           Nullable] public string   ThumbnailPath       { get; set; } // varchar(255)
		[Column,           Nullable] public string   PictureLocalPath    { get; set; } // varchar(255)
		[Column,           Nullable] public string   ThumbnailLocalPath  { get; set; } // varchar(255)
		[Column,           Nullable] public long?    Colors              { get; set; } // integer
		[Column,        NotNull    ] public long     FavoriteNo          { get; set; } // integer
		[Column,           Nullable] public string   UnitName            { get; set; } // varchar(50)
		[Column,           Nullable] public string   RegularSizeName     { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal  EstimateCost        { get; set; } // numeric
		[Column,        NotNull    ] public decimal  Price               { get; set; } // numeric
		[Column,        NotNull    ] public char     OptSalePrice        { get; set; } // varchar(1)
		[Column,        NotNull    ] public char     TaxType             { get; set; } // varchar(1)
		[Column,        NotNull    ] public char     SellBy              { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  FTrackStock         { get; set; } // numeric
		[Column,        NotNull    ] public decimal  FDisplayOption      { get; set; } // numeric
		[Column,        NotNull    ] public DateTime TrackStockDateTime  { get; set; } // datetime
		[Column,        NotNull    ] public char     SaleItemType        { get; set; } // varchar(1)
		[Column,           Nullable] public string   Comments            { get; set; } // varchar(255)
		[Column,        NotNull    ] public DateTime LastDateModified    { get; set; } // datetime
		[Column,        NotNull    ] public string   UserLastModified    { get; set; } // varchar(50)
		[Column,        NotNull    ] public char     DataStatus          { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  FWaitSending        { get; set; } // numeric
		[Column,        NotNull    ] public DateTime WaitSendingTime     { get; set; } // datetime
		[Column,           Nullable] public string   LinkProMaxxItemID   { get; set; } // varchar(50)
		[Column,           Nullable] public string   LinkProMaxxItemUnit { get; set; } // varchar(50)
	}

	[Table("ItemExSize")]
	public partial class ItemExSize
	{
		[PrimaryKey(0), NotNull    ] public long    MerchantID   { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long    SysItemID    { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public long    ExSizeNo     { get; set; } // integer
		[Column,        NotNull    ] public string  ExSizeName   { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal Price        { get; set; } // numeric
		[Column,        NotNull    ] public decimal EstimateCost { get; set; } // numeric
		[Column,           Nullable] public string  Comments     { get; set; } // varchar(255)
	}

	[Table("ItemOnBranch")]
	public partial class ItemOnBranch
	{
		[PrimaryKey(0), NotNull] public long     MerchantID           { get; set; } // integer
		[PrimaryKey(1), NotNull] public long     SysBranchID          { get; set; } // integer
		[PrimaryKey(2), NotNull] public long     SysItemID            { get; set; } // integer
		[Column,        NotNull] public decimal  BalanceStock         { get; set; } // numeric
		[Column,        NotNull] public decimal  MinimumStock         { get; set; } // numeric
		[Column,        NotNull] public DateTime LastDateBalanceStock { get; set; } // datetime
	}

	[Table("MemberType")]
	public partial class MemberType
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID      { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     MemberTypeNo    { get; set; } // integer
		[Column,        NotNull    ] public string   MemberTypeName  { get; set; } // varchar(100)
		[Column,        NotNull    ] public decimal  PercentDiscount { get; set; } // numeric
		[Column,        NotNull    ] public DateTime DateModified    { get; set; } // datetime
		[Column,           Nullable] public string   LinkProMaxxID   { get; set; } // varchar(50)
	}

	[Table("Merchant")]
	public partial class Merchant
	{
		[PrimaryKey, NotNull    ] public long      MerchantID          { get; set; } // integer
		[Column,     NotNull    ] public string    Name                { get; set; } // varchar(250)
		[Column,     NotNull    ] public decimal   FMasterMerchant     { get; set; } // numeric
		[Column,     NotNull    ] public long      RefMasterMerchantID { get; set; } // integer
		[Column,        Nullable] public string    LogoPath            { get; set; } // varchar(250)
		[Column,        Nullable] public string    LogoLocalPath       { get; set; } // varchar(255)
		[Column,     NotNull    ] public char      Status              { get; set; } // varchar(1)
		[Column,     NotNull    ] public DateTime  DateOpenMerchant    { get; set; } // date
		[Column,        Nullable] public DateTime? DateCloseMerchant   { get; set; } // date
		[Column,     NotNull    ] public string    RefPackageID        { get; set; } // varchar(25)
		[Column,     NotNull    ] public long      DayOfPeriod         { get; set; } // integer
		[Column,     NotNull    ] public DateTime  DueDate             { get; set; } // date
		[Column,     NotNull    ] public string    LanguageCountryCode { get; set; } // varchar(50)
		[Column,     NotNull    ] public string    TimeZoneName        { get; set; } // varchar(50)
		[Column,     NotNull    ] public decimal   TimeZoneUTCOffset   { get; set; } // numeric
		[Column,     NotNull    ] public char      FTermConditions     { get; set; } // varchar(1)
		[Column,     NotNull    ] public char      FPrivacyPolicy      { get; set; } // varchar(1)
		[Column,        Nullable] public string    TaxID               { get; set; } // varchar(50)
		[Column,        Nullable] public string    RegMark             { get; set; } // varchar(50)
		[Column,     NotNull    ] public DateTime  DateCreated         { get; set; } // datetime
		[Column,     NotNull    ] public DateTime  DateModified        { get; set; } // datetime
		[Column,     NotNull    ] public string    UserNameModified    { get; set; } // varchar(50)
	}

	[Table("MerchantConfig")]
	public partial class MerchantConfig
	{
		[PrimaryKey(0), NotNull    ] public long      MerchantID { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public string    CfgKey     { get; set; } // varchar(50)
		[Column,           Nullable] public string    CfgString  { get; set; } // varchar(255)
		[Column,           Nullable] public long?     CfgInteger { get; set; } // integer
		[Column,           Nullable] public decimal?  CfgFloat   { get; set; } // numeric
		[Column,           Nullable] public DateTime? CfgDate    { get; set; } // date
	}

	[Table("MyQrCode")]
	public partial class MyQrCode
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID       { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     MyQrCodeNo       { get; set; } // integer
		[Column,           Nullable] public long?    Ordinary         { get; set; } // integer
		[Column,        NotNull    ] public string   MyQrCodeName     { get; set; } // varchar(100)
		[Column,        NotNull    ] public char     FMyQrAllBranch   { get; set; } // varchar(1)
		[Column,           Nullable] public long?    SysBranchID      { get; set; } // integer
		[Column,           Nullable] public string   PicturePath      { get; set; } // varchar(255)
		[Column,           Nullable] public string   PictureLocalPath { get; set; } // varchar(255)
		[Column,           Nullable] public string   Comments         { get; set; } // varchar(255)
		[Column,        NotNull    ] public DateTime DateCreated      { get; set; } // datetime
		[Column,        NotNull    ] public DateTime DateModified     { get; set; } // datetime
		[Column,        NotNull    ] public string   UserNameModified { get; set; } // varchar(50)
	}

	[Table("Note")]
	public partial class Note
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID        { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysNoteID         { get; set; } // integer
		[Column,           Nullable] public long?    Ordinary          { get; set; } // integer
		[Column,        NotNull    ] public string   Message           { get; set; } // varchar(25)
		[Column,           Nullable] public long?    SysNoteCategoryID { get; set; } // integer
		[Column,        NotNull    ] public DateTime LastDateModified  { get; set; } // datetime
		[Column,        NotNull    ] public string   UserLastModified  { get; set; } // varchar(50)
		[Column,        NotNull    ] public char     DataStatus        { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  FWaitSending      { get; set; } // numeric
		[Column,        NotNull    ] public DateTime WaitSendingTime   { get; set; } // datetime
	}

	[Table("NoteCategory")]
	public partial class NoteCategory
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID        { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysNoteCategoryID { get; set; } // integer
		[Column,           Nullable] public long?    Ordinary          { get; set; } // integer
		[Column,        NotNull    ] public string   Name              { get; set; } // varchar(100)
		[Column,        NotNull    ] public DateTime DateCreated       { get; set; } // datetime
		[Column,        NotNull    ] public DateTime DateModified      { get; set; } // datetime
		[Column,        NotNull    ] public char     DataStatus        { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  FWaitSending      { get; set; } // numeric
		[Column,        NotNull    ] public DateTime WaitSendingTime   { get; set; } // datetime
	}

	[Table("ScriptAlterMerchantDB")]
	public partial class ScriptAlterMerchantDB
	{
		[PrimaryKey(0), NotNull    ] public long   ErVersionNo     { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long   DetailNo        { get; set; } // integer
		[Column,        NotNull    ] public string ScriptAlter     { get; set; } // varchar(1000)
		[Column,        NotNull    ] public string ErVersionDBInfo { get; set; } // varchar(255)
		[Column,           Nullable] public string Comments        { get; set; } // varchar(255)
	}

	[Table("SystemInfo")]
	public partial class SystemInfo
	{
		[PrimaryKey, NotNull] public long   SystemID { get; set; } // integer
		[Column,     NotNull] public string Name     { get; set; } // varchar(250)
	}

	[Table("SystemRevisionNo")]
	public partial class SystemRevisionNo
	{
		[PrimaryKey(0), NotNull] public long MerchantID     { get; set; } // integer
		[PrimaryKey(1), NotNull] public long SystemID       { get; set; } // integer
		[Column,        NotNull] public long LastRevisionNo { get; set; } // integer
	}

	[Table("Trans")]
	public partial class Tran
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID           { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysBranchID          { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public string   TranNo               { get; set; } // varchar(25)
		[Column,        NotNull    ] public DateTime TranDate             { get; set; } // datetime
		[Column,        NotNull    ] public char     TranType             { get; set; } // varchar(1)
		[Column,           Nullable] public string   OrderName            { get; set; } // varchar(50)
		[Column,        NotNull    ] public long     Status               { get; set; } // integer
		[Column,           Nullable] public string   POSID                { get; set; } // varchar(50)
		[Column,        NotNull    ] public long     DeviceNo             { get; set; } // integer
		[Column,        NotNull    ] public long     SysCustomerID        { get; set; } // integer
		[Column,        NotNull    ] public string   CustomerName         { get; set; } // varchar(255)
		[Column,           Nullable] public string   GiftMemberCardNo     { get; set; } // varchar(25)
		[Column,           Nullable] public string   EarningInfo          { get; set; } // varchar(100)
		[Column,        NotNull    ] public string   SellerName           { get; set; } // varchar(50)
		[Column,        NotNull    ] public DateTime LastDateModified     { get; set; } // datetime
		[Column,        NotNull    ] public string   LastUserModified     { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal  FCancel              { get; set; } // numeric
		[Column,        NotNull    ] public char     TranTaxType          { get; set; } // varchar(1)
		[Column,           Nullable] public decimal? TaxRate              { get; set; } // numeric
		[Column,        NotNull    ] public long     CountTradDisc        { get; set; } // integer
		[Column,        NotNull    ] public decimal  SubTotalNoneVat      { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalTradDiscNoneVat { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalNoneVat         { get; set; } // numeric
		[Column,        NotNull    ] public decimal  SubTotalHaveVat      { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalTradDiscHaveVat { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalHaveVat         { get; set; } // numeric
		[Column,        NotNull    ] public decimal  Total                { get; set; } // numeric
		[Column,           Nullable] public string   FmlServiceCharge     { get; set; } // varchar(100)
		[Column,        NotNull    ] public decimal  ServiceCharge        { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalVat             { get; set; } // numeric
		[Column,        NotNull    ] public decimal  GrandTotal           { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalProfit          { get; set; } // numeric
		[Column,        NotNull    ] public decimal  PaymentFractional    { get; set; } // numeric
		[Column,        NotNull    ] public decimal  GrandPayment         { get; set; } // numeric
		[Column,        NotNull    ] public decimal  SummaryPayment       { get; set; } // numeric
		[Column,        NotNull    ] public decimal  Change               { get; set; } // numeric
		[Column,        NotNull    ] public decimal  Tips                 { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalPointEarning    { get; set; } // numeric
		[Column,        NotNull    ] public long     PrintCounter         { get; set; } // integer
		[Column,        NotNull    ] public long     PrintCounterLocal    { get; set; } // integer
		[Column,        NotNull    ] public decimal  FWaitSending         { get; set; } // numeric
		[Column,        NotNull    ] public DateTime WaitSendingTime      { get; set; } // datetime
		[Column,        NotNull    ] public char     LocalDataStatus      { get; set; } // varchar(1)
		[Column,           Nullable] public string   Comments             { get; set; } // varchar(255)
	}

	[Table("TranDetailItem")]
	public partial class TranDetailItem
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID             { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysBranchID            { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public string   TranNo                 { get; set; } // varchar(25)
		[PrimaryKey(3), NotNull    ] public long     DetailNo               { get; set; } // integer
		[Column,           Nullable] public long?    CumulativeSum          { get; set; } // integer
		[Column,        NotNull    ] public string   ItemName               { get; set; } // varchar(255)
		[Column,           Nullable] public long?    SysItemID              { get; set; } // integer
		[Column,        NotNull    ] public char     SaleItemType           { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  FProcess               { get; set; } // numeric
		[Column,        NotNull    ] public char     TaxType                { get; set; } // varchar(1)
		[Column,           Nullable] public string   UnitName               { get; set; } // varchar(50)
		[Column,           Nullable] public string   SizeName               { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal  Quantity               { get; set; } // numeric
		[Column,           Nullable] public decimal? Weight                 { get; set; } // numeric
		[Column,           Nullable] public string   WeightUnitName         { get; set; } // varchar(50)
		[Column,           Nullable] public decimal? PricePerWeight         { get; set; } // numeric
		[Column,        NotNull    ] public decimal  ItemPrice              { get; set; } // numeric
		[Column,        NotNull    ] public decimal  Price                  { get; set; } // numeric
		[Column,        NotNull    ] public decimal  SumToppingPrice        { get; set; } // numeric
		[Column,        NotNull    ] public decimal  SubAmount              { get; set; } // numeric
		[Column,           Nullable] public string   FmlDiscountRow         { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal  Discount               { get; set; } // numeric
		[Column,        NotNull    ] public decimal  DiscountPromotion      { get; set; } // numeric
		[Column,        NotNull    ] public decimal  DiscountRedeem         { get; set; } // numeric
		[Column,           Nullable] public string   RedeemCode             { get; set; } // varchar(100)
		[Column,        NotNull    ] public decimal  Amount                 { get; set; } // numeric
		[Column,        NotNull    ] public decimal  VatAmount              { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TaxBaseAmount          { get; set; } // numeric
		[Column,        NotNull    ] public decimal  WeightTranDisc         { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TotalPrice             { get; set; } // numeric
		[Column,        NotNull    ] public decimal  EstimateCost           { get; set; } // numeric
		[Column,        NotNull    ] public decimal  SumToppingEstimateCost { get; set; } // numeric
		[Column,        NotNull    ] public decimal  ProfitAmount           { get; set; } // numeric
		[Column,           Nullable] public string   Comments               { get; set; } // varchar(255)
	}

	[Table("TranDetailItemTopping")]
	public partial class TranDetailItemTopping
	{
		[PrimaryKey(0), NotNull    ] public long    MerchantID      { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long    SysBranchID     { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public string  TranNo          { get; set; } // varchar(25)
		[PrimaryKey(3), NotNull    ] public long    DetailNo        { get; set; } // integer
		[PrimaryKey(4), NotNull    ] public long    ToppingNo       { get; set; } // integer
		[Column,        NotNull    ] public string  ItemName        { get; set; } // varchar(255)
		[Column,           Nullable] public long?   SysItemID       { get; set; } // integer
		[Column,           Nullable] public string  UnitName        { get; set; } // varchar(50)
		[Column,           Nullable] public string  RegularSizeName { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal Quantity        { get; set; } // numeric
		[Column,        NotNull    ] public decimal ToppingPrice    { get; set; } // numeric
		[Column,        NotNull    ] public decimal EstimateCost    { get; set; } // numeric
		[Column,           Nullable] public string  Comments        { get; set; } // varchar(255)
	}

	[Table("TranPayment")]
	public partial class TranPayment
	{
		[PrimaryKey(0), NotNull    ] public long      MerchantID       { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long      SysBranchID      { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public string    TranNo           { get; set; } // varchar(25)
		[PrimaryKey(3), NotNull    ] public long      PaymentNo        { get; set; } // integer
		[Column,        NotNull    ] public string    PaymentType      { get; set; } // varchar(4)
		[Column,        NotNull    ] public decimal   PaymentAmount    { get; set; } // numeric
		[Column,           Nullable] public string    CreditCardType   { get; set; } // varchar(10)
		[Column,           Nullable] public string    CardNo           { get; set; } // varchar(25)
		[Column,           Nullable] public string    ExprieDateYYYYMM { get; set; } // varchar(6)
		[Column,           Nullable] public string    ApproveCode      { get; set; } // varchar(25)
		[Column,           Nullable] public decimal?  TotalRedeemPoint { get; set; } // numeric
		[Column,           Nullable] public string    RequestNum       { get; set; } // varchar(50)
		[Column,           Nullable] public DateTime? RequestDateTime  { get; set; } // datetime
		[Column,           Nullable] public decimal?  FEPaymentCancel  { get; set; } // numeric
		[Column,           Nullable] public string    ReferenceNo1     { get; set; } // varchar(255)
		[Column,           Nullable] public string    ReferenceNo2     { get; set; } // varchar(255)
		[Column,           Nullable] public string    ReferenceNo3     { get; set; } // varchar(255)
		[Column,           Nullable] public string    ReferenceNo4     { get; set; } // varchar(255)
		[Column,           Nullable] public string    PicturePath      { get; set; } // varchar(255)
		[Column,           Nullable] public string    Comments         { get; set; } // varchar(255)
	}

	[Table("TransPoint")]
	public partial class TransPoint
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID       { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysBranchID      { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public string   TransPointNo     { get; set; } // varchar(25)
		[Column,           Nullable] public string   RefTranNo        { get; set; } // varchar(25)
		[Column,        NotNull    ] public char     TransPointType   { get; set; } // varchar(1)
		[Column,        NotNull    ] public decimal  TranAmount       { get; set; } // numeric
		[Column,        NotNull    ] public decimal  CalcAmount       { get; set; } // numeric
		[Column,        NotNull    ] public decimal  PointExtra       { get; set; } // numeric
		[Column,        NotNull    ] public decimal  PointAmount      { get; set; } // numeric
		[Column,           Nullable] public string   EarningRateCalc  { get; set; } // varchar(25)
		[Column,           Nullable] public string   Comments         { get; set; } // varchar(255)
		[Column,        NotNull    ] public DateTime LastDateModified { get; set; } // datetime
	}

	[Table("TranTradDiscount")]
	public partial class TranTradDiscount
	{
		[PrimaryKey(0), NotNull    ] public long     MerchantID       { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public long     SysBranchID      { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public string   TranNo           { get; set; } // varchar(25)
		[PrimaryKey(3), NotNull    ] public long     TradDiscountNo   { get; set; } // integer
		[Column,        NotNull    ] public long     PriorityNo       { get; set; } // integer
		[Column,        NotNull    ] public decimal  FOnTop           { get; set; } // numeric
		[Column,        NotNull    ] public string   DiscountType     { get; set; } // varchar(2)
		[Column,        NotNull    ] public string   FmlDiscount      { get; set; } // varchar(50)
		[Column,        NotNull    ] public decimal  TradeDiscNoneVat { get; set; } // numeric
		[Column,        NotNull    ] public decimal  TradeDiscHaveVat { get; set; } // numeric
		[Column,           Nullable] public decimal? TotalRedeemPoint { get; set; } // numeric
		[Column,           Nullable] public string   ReferenceNo1     { get; set; } // varchar(255)
		[Column,           Nullable] public string   ReferenceNo2     { get; set; } // varchar(255)
		[Column,           Nullable] public string   ReferenceNo3     { get; set; } // varchar(255)
		[Column,           Nullable] public string   Comments         { get; set; } // varchar(255)
	}

	[Table("UserAccountInfo")]
	public partial class UserAccountInfo
	{
		[PrimaryKey(0), NotNull    ] public long   MerchantID  { get; set; } // integer
		[PrimaryKey(1), NotNull    ] public string UserName    { get; set; } // varchar(50)
		[Column,        NotNull    ] public long   FUsePincode { get; set; } // integer
		[Column,           Nullable] public string PinCode     { get; set; } // varchar(100)
		[Column,           Nullable] public string Comments    { get; set; } // varchar(255)
	}

	public static partial class TableExtensions
	{
		public static AppConfig Find(this ITable<AppConfig> table, string CfgKey)
		{
			return table.FirstOrDefault(t =>
				t.CfgKey == CfgKey);
		}

		public static Branch Find(this ITable<Branch> table, long MerchantID, long SysBranchID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID &&
				t.SysBranchID == SysBranchID);
		}

		public static BranchPolicy Find(this ITable<BranchPolicy> table, long MerchantID, string UserName, long SysBranchID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID &&
				t.UserName    == UserName   &&
				t.SysBranchID == SysBranchID);
		}

		public static CashTemplate Find(this ITable<CashTemplate> table, long MerchantID, long CashTemplateNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID     == MerchantID &&
				t.CashTemplateNo == CashTemplateNo);
		}

		public static Category Find(this ITable<Category> table, long MerchantID, long SysCategoryID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID    == MerchantID &&
				t.SysCategoryID == SysCategoryID);
		}

		public static Customer Find(this ITable<Customer> table, long MerchantID, long SysCustomerID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID    == MerchantID &&
				t.SysCustomerID == SysCustomerID);
		}

		public static DataBaseInfo Find(this ITable<DataBaseInfo> table, string KeyDBInfo)
		{
			return table.FirstOrDefault(t =>
				t.KeyDBInfo == KeyDBInfo);
		}

		public static DeviceSystemSeqNo Find(this ITable<DeviceSystemSeqNo> table, long MerchantID, long DeviceNo, long SystemID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.DeviceNo   == DeviceNo   &&
				t.SystemID   == SystemID);
		}

		public static DeviceTranRunningNo Find(this ITable<DeviceTranRunningNo> table, long MerchantID, long SysBranchID, long DeviceNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID  &&
				t.SysBranchID == SysBranchID &&
				t.DeviceNo    == DeviceNo);
		}

		public static DiscountTemplate Find(this ITable<DiscountTemplate> table, long MerchantID, long SysDiscountTemplate)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID          == MerchantID &&
				t.SysDiscountTemplate == SysDiscountTemplate);
		}

		public static GiftVoucher Find(this ITable<GiftVoucher> table, long MerchantID, string GiftVoucherCode)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID      == MerchantID &&
				t.GiftVoucherCode == GiftVoucherCode);
		}

		public static Item Find(this ITable<Item> table, long MerchantID, long SysItemID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.SysItemID  == SysItemID);
		}

		public static ItemExSize Find(this ITable<ItemExSize> table, long MerchantID, long SysItemID, long ExSizeNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.SysItemID  == SysItemID  &&
				t.ExSizeNo   == ExSizeNo);
		}

		public static ItemOnBranch Find(this ITable<ItemOnBranch> table, long MerchantID, long SysBranchID, long SysItemID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID  &&
				t.SysBranchID == SysBranchID &&
				t.SysItemID   == SysItemID);
		}

		public static MemberType Find(this ITable<MemberType> table, long MerchantID, long MemberTypeNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID   == MerchantID &&
				t.MemberTypeNo == MemberTypeNo);
		}

		public static Merchant Find(this ITable<Merchant> table, long MerchantID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID);
		}

		public static MerchantConfig Find(this ITable<MerchantConfig> table, long MerchantID, string CfgKey)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.CfgKey     == CfgKey);
		}

		public static MyQrCode Find(this ITable<MyQrCode> table, long MerchantID, long MyQrCodeNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.MyQrCodeNo == MyQrCodeNo);
		}

		public static Note Find(this ITable<Note> table, long MerchantID, long SysNoteID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.SysNoteID  == SysNoteID);
		}

		public static NoteCategory Find(this ITable<NoteCategory> table, long MerchantID, long SysNoteCategoryID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID        == MerchantID &&
				t.SysNoteCategoryID == SysNoteCategoryID);
		}

		public static ScriptAlterMerchantDB Find(this ITable<ScriptAlterMerchantDB> table, long ErVersionNo, long DetailNo)
		{
			return table.FirstOrDefault(t =>
				t.ErVersionNo == ErVersionNo &&
				t.DetailNo    == DetailNo);
		}

		public static SystemInfo Find(this ITable<SystemInfo> table, long SystemID)
		{
			return table.FirstOrDefault(t =>
				t.SystemID == SystemID);
		}

		public static SystemRevisionNo Find(this ITable<SystemRevisionNo> table, long MerchantID, long SystemID)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.SystemID   == SystemID);
		}

		public static Tran Find(this ITable<Tran> table, long MerchantID, long SysBranchID, string TranNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID  &&
				t.SysBranchID == SysBranchID &&
				t.TranNo      == TranNo);
		}

		public static TranDetailItem Find(this ITable<TranDetailItem> table, long MerchantID, long SysBranchID, string TranNo, long DetailNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID  &&
				t.SysBranchID == SysBranchID &&
				t.TranNo      == TranNo      &&
				t.DetailNo    == DetailNo);
		}

		public static TranDetailItemTopping Find(this ITable<TranDetailItemTopping> table, long MerchantID, long SysBranchID, string TranNo, long DetailNo, long ToppingNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID  &&
				t.SysBranchID == SysBranchID &&
				t.TranNo      == TranNo      &&
				t.DetailNo    == DetailNo    &&
				t.ToppingNo   == ToppingNo);
		}

		public static TranPayment Find(this ITable<TranPayment> table, long MerchantID, long SysBranchID, string TranNo, long PaymentNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID  == MerchantID  &&
				t.SysBranchID == SysBranchID &&
				t.TranNo      == TranNo      &&
				t.PaymentNo   == PaymentNo);
		}

		public static TransPoint Find(this ITable<TransPoint> table, long MerchantID, long SysBranchID, string TransPointNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID   == MerchantID  &&
				t.SysBranchID  == SysBranchID &&
				t.TransPointNo == TransPointNo);
		}

		public static TranTradDiscount Find(this ITable<TranTradDiscount> table, long MerchantID, long SysBranchID, string TranNo, long TradDiscountNo)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID     == MerchantID  &&
				t.SysBranchID    == SysBranchID &&
				t.TranNo         == TranNo      &&
				t.TradDiscountNo == TradDiscountNo);
		}

		public static UserAccountInfo Find(this ITable<UserAccountInfo> table, long MerchantID, string UserName)
		{
			return table.FirstOrDefault(t =>
				t.MerchantID == MerchantID &&
				t.UserName   == UserName);
		}
	}
}

#pragma warning restore 1591
  